import { ClientCreationAttributes } from "./entities/client-entity";

export const testData: ClientCreationAttributes[] = [
	{
		firstName: "Fuller",
		lastName: "Irwin",
		phone: "402-6375",
		email: "volutpat.ornare@duinec.edu",
		street: "P.O. Box 843, 7801 Vitae, St.",
		city: "Ahmedabad",
		postalCode: "16-959",
		country: "Gibraltar",
		isActive: false,
	},
	{
		firstName: "Grady",
		lastName: "Barrett",
		phone: "1-758-989-6710",
		email: "Aenean.sed.pede@magna.co.uk",
		street: "Ap #932-3948 Auctor Street",
		city: "Laurencekirk",
		postalCode: "4075",
		country: "Taiwan",
		isActive: false,
	},
	{
		firstName: "Wade",
		lastName: "Alford",
		phone: "204-4584",
		email: "adipiscing.Mauris.molestie@sitametrisus.co.uk",
		street: "2117 Dis Av.",
		city: "Armento",
		postalCode: "RO07 8MJ",
		country: "Namibia",
		isActive: true,
	},
	{
		firstName: "Vanna",
		lastName: "Whitfield",
		phone: "712-6548",
		email: "metus.urna@consectetueradipiscingelit.net",
		street: "Ap #636-9003 Ac Street",
		city: "Sainte-Ode",
		postalCode: "2919 WA",
		country: "Bolivia",
		isActive: false,
	},
	{
		firstName: "Murphy",
		lastName: "Gardner",
		phone: "1-379-509-5893",
		email: "quam.elementum.at@ipsum.edu",
		street: "Ap #518-1036 Magna. Street",
		city: "Stalhille",
		postalCode: "332954",
		country: "Austria",
		isActive: false,
	},
	{
		firstName: "Cara",
		lastName: "Foley",
		phone: "1-644-186-9404",
		email: "quis.turpis.vitae@ante.com",
		street: "Ap #826-7972 Fermentum St.",
		city: "Sacramento",
		postalCode: "6176",
		country: "Guatemala",
		isActive: false,
	},
	{
		firstName: "Alfonso",
		lastName: "Heath",
		phone: "1-720-967-5042",
		email: "malesuada.augue.ut@aliquam.co.uk",
		street: "998 Vitae Rd.",
		city: "Sala Baganza",
		postalCode: "26364",
		country: "Haiti",
		isActive: true,
	},
	{
		firstName: "Kenneth",
		lastName: "Ball",
		phone: "1-510-714-4834",
		email: "dignissim.tempor.arcu@risus.org",
		street: "1407 Pellentesque Rd.",
		city: "Heidelberg",
		postalCode: "E8A 5Z8",
		country: "Viet Nam",
		isActive: false,
	},
	{
		firstName: "Julian",
		lastName: "Bauer",
		phone: "967-7801",
		email: "velit.Aliquam@disparturientmontes.edu",
		street: "3483 Nulla Rd.",
		city: "Jiutepec",
		postalCode: "194507",
		country: "French Guiana",
		isActive: true,
	},
	{
		firstName: "Kyra",
		lastName: "Wiggins",
		phone: "319-6230",
		email: "tortor.nibh@torquent.ca",
		street: "8012 Ipsum. St.",
		city: "Crawley",
		postalCode: "275339",
		country: "Guadeloupe",
		isActive: true,
	},
	{
		firstName: "Harrison",
		lastName: "Petersen",
		phone: "440-3116",
		email: "Aliquam.adipiscing@dui.com",
		street: "8303 Sed St.",
		city: "Annone di Brianza",
		postalCode: "C8A 9W5",
		country: "Lithuania",
		isActive: true,
	},
	{
		firstName: "Evan",
		lastName: "Stanley",
		phone: "1-772-985-0248",
		email: "penatibus.et@habitant.co.uk",
		street: "P.O. Box 593, 6233 Mollis Ave",
		city: "Carnoustie",
		postalCode: "95-128",
		country: "Lithuania",
		isActive: false,
	},
	{
		firstName: "Ali",
		lastName: "Daniels",
		phone: "333-2462",
		email: "sapien@Praesent.org",
		street: "Ap #102-1319 Lectus St.",
		city: "Mosciano Sant'Angelo",
		postalCode: "36532",
		country: "Solomon Islands",
		isActive: true,
	},
	{
		firstName: "Chaim",
		lastName: "Barker",
		phone: "1-462-281-9324",
		email: "facilisis@orciquis.ca",
		street: "127-7066 Ac St.",
		city: "Callander",
		postalCode: "13115-09372",
		country: "Liechtenstein",
		isActive: false,
	},
	{
		firstName: "Ahmed",
		lastName: "Hurley",
		phone: "1-182-683-9080",
		email: "vestibulum@acmattissemper.net",
		street: "777-3707 Ac Av.",
		city: "Telford",
		postalCode: "31250",
		country: "Andorra",
		isActive: true,
	},
	{
		firstName: "Paul",
		lastName: "King",
		phone: "1-565-917-8207",
		email: "sed.sem@eratvel.edu",
		street: "Ap #248-8135 Consectetuer, Rd.",
		city: "Rves",
		postalCode: "39460",
		country: "Cambodia",
		isActive: true,
	},
	{
		firstName: "Noelani",
		lastName: "Curry",
		phone: "1-119-865-5655",
		email: "euismod@nascetur.net",
		street: "420-7503 Sociis St.",
		city: "Şereflikoçhisar",
		postalCode: "3680",
		country: "Luxembourg",
		isActive: true,
	},
	{
		firstName: "Elizabeth",
		lastName: "Franco",
		phone: "1-232-239-2304",
		email: "lacinia.orci.consectetuer@acmattis.edu",
		street: "8916 Sed Ave",
		city: "Macerata",
		postalCode: "741535",
		country: "Qatar",
		isActive: false,
	},
	{
		firstName: "Evan",
		lastName: "Harrell",
		phone: "1-943-955-7599",
		email: "lacus@odiosempercursus.com",
		street: "9188 Duis Ave",
		city: "Geraldton-Greenough",
		postalCode: "49201",
		country: "Finland",
		isActive: false,
	},
	{
		firstName: "Nora",
		lastName: "Wheeler",
		phone: "733-6168",
		email: "aliquet.lobortis.nisi@sed.org",
		street: "673-7865 Nec Road",
		city: "Duncan",
		postalCode: "128677",
		country: "Antarctica",
		isActive: true,
	},
	{
		firstName: "Paul",
		lastName: "Monroe",
		phone: "1-242-149-7025",
		email: "semper.cursus@imperdietnecleo.com",
		street: "Ap #520-2395 In Avenue",
		city: "Santa Vittoria in Matenano",
		postalCode: "47143",
		country: "Oman",
		isActive: true,
	},
	{
		firstName: "Tamekah",
		lastName: "Nicholson",
		phone: "127-2550",
		email: "condimentum.eget.volutpat@etrutrum.ca",
		street: "779-4932 Ornare. Road",
		city: "Okotoks",
		postalCode: "1899 AD",
		country: "Zambia",
		isActive: false,
	},
	{
		firstName: "Ursa",
		lastName: "Rojas",
		phone: "536-7754",
		email: "dictum@accumsaninterdumlibero.co.uk",
		street: "P.O. Box 752, 9190 Sit Road",
		city: "Tione di Trento",
		postalCode: "81389",
		country: "Central African Republic",
		isActive: true,
	},
	{
		firstName: "Karyn",
		lastName: "Clemons",
		phone: "1-453-772-6609",
		email: "mauris.Suspendisse.aliquet@ullamcorpervelitin.com",
		street: "838-2485 Sapien, Ave",
		city: "Milwaukee",
		postalCode: "98847",
		country: "Monaco",
		isActive: false,
	},
	{
		firstName: "Kelsie",
		lastName: "Buckley",
		phone: "418-9378",
		email: "erat.neque.non@nislQuisque.net",
		street: "654-2558 Laoreet Road",
		city: "Palmira",
		postalCode: "6415 LG",
		country: "Australia",
		isActive: true,
	},
	{
		firstName: "Malik",
		lastName: "Hale",
		phone: "878-0293",
		email: "ultrices@ut.com",
		street: "Ap #386-8051 Diam St.",
		city: "Devonport",
		postalCode: "N83 2KV",
		country: "Cuba",
		isActive: false,
	},
	{
		firstName: "Dane",
		lastName: "Watts",
		phone: "1-339-820-1562",
		email: "egestas@Morbivehicula.org",
		street: "6631 Id, Av.",
		city: "Pasuruan",
		postalCode: "929850",
		country: "Bosnia and Herzegovina",
		isActive: true,
	},
	{
		firstName: "Abbot",
		lastName: "Leon",
		phone: "1-871-458-4578",
		email: "montes.nascetur@quis.org",
		street: "Ap #708-1977 Aliquam Av.",
		city: "Obertshausen",
		postalCode: "5331",
		country: "Bonaire, Sint Eustatius and Saba",
		isActive: true,
	},
	{
		firstName: "Orli",
		lastName: "Hatfield",
		phone: "1-505-289-9400",
		email: "ante.ipsum.primis@lectus.ca",
		street: "Ap #128-8369 Id, Road",
		city: "Ortacesus",
		postalCode: "21500",
		country: "Saint Lucia",
		isActive: true,
	},
	{
		firstName: "Andrew",
		lastName: "Burgess",
		phone: "1-861-628-0668",
		email: "orci@dictummagnaUt.edu",
		street: "300-3948 Aliquam Rd.",
		city: "New Glasgow",
		postalCode: "Z7709",
		country: "Gambia",
		isActive: true,
	},
	{
		firstName: "Hayfa",
		lastName: "Valencia",
		phone: "1-976-476-2818",
		email: "vehicula.et.rutrum@feugiatmetussit.edu",
		street: "P.O. Box 201, 8235 Magnis St.",
		city: "Corbara",
		postalCode: "15032-991",
		country: "British Indian Ocean Territory",
		isActive: false,
	},
	{
		firstName: "Robin",
		lastName: "Cannon",
		phone: "1-441-506-3834",
		email: "Sed.auctor.odio@quisarcu.edu",
		street: "Ap #266-9020 Phasellus St.",
		city: "Opglabbeek",
		postalCode: "645456",
		country: "Slovakia",
		isActive: false,
	},
	{
		firstName: "Dorothy",
		lastName: "Mckenzie",
		phone: "153-8244",
		email: "felis.orci.adipiscing@turpisegestasFusce.com",
		street: "P.O. Box 218, 3638 At Ave",
		city: "Zignago",
		postalCode: "YS39 8MC",
		country: "Morocco",
		isActive: false,
	},
	{
		firstName: "Nicholas",
		lastName: "Kemp",
		phone: "1-249-351-6946",
		email: "Aliquam@Morbinon.co.uk",
		street: "1777 Ut Av.",
		city: "Chilpancingo",
		postalCode: "223740",
		country: "Mauritius",
		isActive: true,
	},
	{
		firstName: "Whitney",
		lastName: "Guthrie",
		phone: "413-2627",
		email: "et.arcu.imperdiet@rhoncusDonec.co.uk",
		street: "P.O. Box 897, 6410 Mauris St.",
		city: "Chiniot",
		postalCode: "9960",
		country: "Macao",
		isActive: true,
	},
	{
		firstName: "Kathleen",
		lastName: "White",
		phone: "1-208-220-1845",
		email: "arcu@accumsanconvallisante.org",
		street: "Ap #634-5622 Rutrum Street",
		city: "Douai",
		postalCode: "417181",
		country: "Antigua and Barbuda",
		isActive: true,
	},
	{
		firstName: "Vera",
		lastName: "Rosales",
		phone: "852-7336",
		email: "dapibus.quam.quis@velarcu.com",
		street: "Ap #956-2624 Laoreet Street",
		city: "Cañete",
		postalCode: "34161",
		country: "United States",
		isActive: true,
	},
	{
		firstName: "Erica",
		lastName: "Ortiz",
		phone: "1-131-160-3189",
		email: "ac@aliquetPhasellusfermentum.co.uk",
		street: "P.O. Box 201, 8678 Arcu. Road",
		city: "Algarrobo",
		postalCode: "43689-32352",
		country: "Uzbekistan",
		isActive: false,
	},
	{
		firstName: "Martin",
		lastName: "Battle",
		phone: "1-766-623-2290",
		email: "faucibus.leo@neque.co.uk",
		street: "Ap #550-927 Ac, St.",
		city: "Washuk",
		postalCode: "4848",
		country: "Congo, the Democratic Republic of the",
		isActive: true,
	},
	{
		firstName: "Cairo",
		lastName: "Larson",
		phone: "1-290-196-0562",
		email: "risus.varius@nonummyutmolestie.edu",
		street: "8121 Cras Av.",
		city: "San Giovanni Lipioni",
		postalCode: "302909",
		country: "Zimbabwe",
		isActive: false,
	},
	{
		firstName: "Joshua",
		lastName: "Harrington",
		phone: "1-993-722-7444",
		email: "sit.amet.nulla@ante.org",
		street: "2393 Egestas Ave",
		city: "Bon Accord",
		postalCode: "6491",
		country: "Algeria",
		isActive: true,
	},
	{
		firstName: "Caleb",
		lastName: "Williams",
		phone: "731-5285",
		email: "in@ullamcorper.co.uk",
		street: "Ap #468-5079 Aenean Rd.",
		city: "Pavlovsky Posad",
		postalCode: "01712",
		country: "Luxembourg",
		isActive: true,
	},
	{
		firstName: "Solomon",
		lastName: "Hubbard",
		phone: "179-5753",
		email: "elementum.sem@lacinia.com",
		street: "4139 Adipiscing Avenue",
		city: "Petacciato",
		postalCode: "027182",
		country: "New Zealand",
		isActive: false,
	},
	{
		firstName: "Phelan",
		lastName: "Sloan",
		phone: "794-5978",
		email: "sagittis.Nullam@mollis.edu",
		street: "904-1740 In Av.",
		city: "Vliermaalroot",
		postalCode: "484871",
		country: "China",
		isActive: false,
	},
	{
		firstName: "Brendan",
		lastName: "Talley",
		phone: "1-971-262-0812",
		email: "luctus.aliquet@felis.org",
		street: "P.O. Box 594, 5714 Amet, Road",
		city: "Lobbes",
		postalCode: "72695",
		country: "Falkland Islands",
		isActive: true,
	},
	{
		firstName: "Marah",
		lastName: "Keller",
		phone: "165-0977",
		email: "iaculis.odio@Duis.co.uk",
		street: "323-4443 Nec Road",
		city: "Gaggio Montano",
		postalCode: "3849 MN",
		country: "Morocco",
		isActive: true,
	},
	{
		firstName: "Galena",
		lastName: "Young",
		phone: "814-9487",
		email: "amet@duiCumsociis.com",
		street: "P.O. Box 957, 2819 Cras Rd.",
		city: "Felixstowe",
		postalCode: "281826",
		country: "Ethiopia",
		isActive: true,
	},
	{
		firstName: "Melyssa",
		lastName: "Nunez",
		phone: "710-0375",
		email: "Vivamus.non@sedconsequat.ca",
		street: "9873 Consectetuer Av.",
		city: "Fermont",
		postalCode: "431784",
		country: "Laos",
		isActive: true,
	},
	{
		firstName: "Nyssa",
		lastName: "Alston",
		phone: "1-898-318-6417",
		email: "est@elitNulla.ca",
		street: "Ap #552-4914 Phasellus Rd.",
		city: "Montague",
		postalCode: "41907",
		country: "Kenya",
		isActive: true,
	},
	{
		firstName: "Dante",
		lastName: "Lancaster",
		phone: "1-138-316-7384",
		email: "molestie.tellus.Aenean@amet.net",
		street: "470-7459 Fusce Street",
		city: "Independence",
		postalCode: "Z1252",
		country: "Iran",
		isActive: false,
	},
	{
		firstName: "Rowan",
		lastName: "Mccarthy",
		phone: "825-3236",
		email: "Ut@facilisisnon.org",
		street: "339-6530 Auctor Street",
		city: "Kaaskerke",
		postalCode: "57322-72346",
		country: "Qatar",
		isActive: true,
	},
	{
		firstName: "Illana",
		lastName: "Rasmussen",
		phone: "423-4993",
		email: "risus.In@amet.co.uk",
		street: "Ap #135-4705 Non Avenue",
		city: "Akron",
		postalCode: "80986",
		country: "Luxembourg",
		isActive: true,
	},
	{
		firstName: "Quincy",
		lastName: "Estrada",
		phone: "915-1999",
		email: "Proin.eget.odio@mattissemper.com",
		street: "2865 Neque. St.",
		city: "Laakirchen",
		postalCode: "974527",
		country: "Haiti",
		isActive: false,
	},
	{
		firstName: "Raja",
		lastName: "Mcbride",
		phone: "961-2243",
		email: "laoreet@arcu.net",
		street: "7997 Netus Street",
		city: "Savannah",
		postalCode: "30512",
		country: "Turkmenistan",
		isActive: false,
	},
	{
		firstName: "Oren",
		lastName: "Farmer",
		phone: "1-419-252-5866",
		email: "eget@Aliquam.net",
		street: "P.O. Box 265, 3879 Nulla Road",
		city: "Clarksville",
		postalCode: "26997",
		country: "Venezuela",
		isActive: false,
	},
	{
		firstName: "Lucy",
		lastName: "Carson",
		phone: "527-5456",
		email: "dictum.sapien.Aenean@liberoDonec.co.uk",
		street: "Ap #909-2551 Quis Rd.",
		city: "Lodine",
		postalCode: "46-930",
		country: "Bermuda",
		isActive: false,
	},
	{
		firstName: "Teegan",
		lastName: "Cochran",
		phone: "1-672-187-8434",
		email: "Suspendisse@vel.net",
		street: "P.O. Box 908, 5091 Ultricies Rd.",
		city: "Wierde",
		postalCode: "680263",
		country: "Saint Pierre and Miquelon",
		isActive: true,
	},
	{
		firstName: "Quamar",
		lastName: "Mcbride",
		phone: "1-137-767-7861",
		email: "erat.nonummy.ultricies@natoquepenatibuset.org",
		street: "478-3921 Dui Street",
		city: "Guilmi",
		postalCode: "EN1 3EW",
		country: "Greece",
		isActive: true,
	},
	{
		firstName: "Hadley",
		lastName: "Powell",
		phone: "741-0035",
		email: "cursus.luctus@magnaLorem.net",
		street: "Ap #911-6594 Nam Rd.",
		city: "Opglabbeek",
		postalCode: "801175",
		country: "Lebanon",
		isActive: false,
	},
	{
		firstName: "Alma",
		lastName: "Bishop",
		phone: "729-9991",
		email: "Quisque.tincidunt@metusAliquam.com",
		street: "Ap #207-1396 Neque Ave",
		city: "Millet",
		postalCode: "L3N 0K4",
		country: "Morocco",
		isActive: false,
	},
	{
		firstName: "Sage",
		lastName: "Strong",
		phone: "1-940-610-3358",
		email: "nec@ultrices.ca",
		street: "P.O. Box 868, 8575 Ut St.",
		city: "Casciana Terme",
		postalCode: "41915",
		country: "Timor-Leste",
		isActive: false,
	},
	{
		firstName: "Bianca",
		lastName: "Shepherd",
		phone: "605-2022",
		email: "egestas.nunc.sed@dictummagna.org",
		street: "Ap #244-7608 Aenean Av.",
		city: "Latinne",
		postalCode: "883516",
		country: "Uzbekistan",
		isActive: false,
	},
	{
		firstName: "Hedwig",
		lastName: "Rowland",
		phone: "1-125-303-5447",
		email: "velit@ProinvelitSed.ca",
		street: "7112 Sollicitudin Avenue",
		city: "Cañete",
		postalCode: "17918-32116",
		country: "Anguilla",
		isActive: false,
	},
	{
		firstName: "Brody",
		lastName: "Hays",
		phone: "140-2491",
		email: "molestie@natoquepenatibuset.ca",
		street: "P.O. Box 381, 3511 Sed, St.",
		city: "Essex",
		postalCode: "64360",
		country: "Uzbekistan",
		isActive: false,
	},
	{
		firstName: "Caesar",
		lastName: "Gaines",
		phone: "623-3267",
		email: "amet.faucibus.ut@tellus.org",
		street: "5775 Cras Ave",
		city: "Blagoveshchensk",
		postalCode: "167354",
		country: "Mexico",
		isActive: true,
	},
	{
		firstName: "Kibo",
		lastName: "Hess",
		phone: "230-1953",
		email: "Quisque.imperdiet.erat@faucibus.ca",
		street: "427-5933 Gravida. Ave",
		city: "Dordrecht",
		postalCode: "31210",
		country: "Honduras",
		isActive: true,
	},
	{
		firstName: "Theodore",
		lastName: "Mcgowan",
		phone: "1-254-423-8191",
		email: "arcu.ac@elit.net",
		street: "884-7016 Vivamus Road",
		city: "Gruitrode",
		postalCode: "67552",
		country: "Uruguay",
		isActive: true,
	},
	{
		firstName: "Bevis",
		lastName: "Hammond",
		phone: "332-6781",
		email: "ut.mi@mauris.ca",
		street: "P.O. Box 686, 8097 Dui. Road",
		city: "Hyères",
		postalCode: "08168-14046",
		country: "Sri Lanka",
		isActive: true,
	},
	{
		firstName: "Clark",
		lastName: "Roy",
		phone: "1-102-479-2622",
		email: "sit.amet@adipiscing.org",
		street: "2451 Nunc Rd.",
		city: "Halen",
		postalCode: "489015",
		country: "Luxembourg",
		isActive: false,
	},
	{
		firstName: "Macey",
		lastName: "Morin",
		phone: "1-562-641-1711",
		email: "ridiculus@justoeuarcu.net",
		street: "P.O. Box 465, 7872 Non Road",
		city: "Vitrival",
		postalCode: "6941",
		country: "Liechtenstein",
		isActive: true,
	},
	{
		firstName: "Claudia",
		lastName: "Blackwell",
		phone: "180-1224",
		email: "accumsan.convallis@milacinia.net",
		street: "569-4162 Tincidunt Rd.",
		city: "Sepino",
		postalCode: "688420",
		country: "Myanmar",
		isActive: false,
	},
	{
		firstName: "MacKenzie",
		lastName: "Mayo",
		phone: "1-277-944-3114",
		email: "volutpat@nisidictumaugue.co.uk",
		street: "175-2938 Aliquam Avenue",
		city: "Mejillones",
		postalCode: "38350",
		country: "South Africa",
		isActive: true,
	},
	{
		firstName: "Dahlia",
		lastName: "Kelly",
		phone: "1-593-930-0678",
		email: "Duis.volutpat.nunc@Curabituregestas.ca",
		street: "173-1797 Integer St.",
		city: "Francofonte",
		postalCode: "74412",
		country: "Tajikistan",
		isActive: true,
	},
	{
		firstName: "Ariel",
		lastName: "Cohen",
		phone: "1-647-331-3914",
		email: "arcu.Nunc.mauris@miDuis.co.uk",
		street: "P.O. Box 361, 6884 Maecenas Ave",
		city: "Los Lagos",
		postalCode: "96036",
		country: "Falkland Islands",
		isActive: true,
	},
	{
		firstName: "Jason",
		lastName: "Perry",
		phone: "567-6490",
		email: "Praesent.eu.nulla@orcitincidunt.com",
		street: "Ap #701-8463 Sed Avenue",
		city: "Villamassargia",
		postalCode: "10627",
		country: "Hong Kong",
		isActive: false,
	},
	{
		firstName: "Ahmed",
		lastName: "Munoz",
		phone: "406-2359",
		email: "Vivamus.nisi.Mauris@sem.co.uk",
		street: "857-3333 Vel Av.",
		city: "Segovia",
		postalCode: "4523",
		country: "Bulgaria",
		isActive: false,
	},
	{
		firstName: "Venus",
		lastName: "Bryan",
		phone: "329-4422",
		email: "quis@faucibusorci.net",
		street: "292-7192 Rutrum St.",
		city: "San Juan de Girón",
		postalCode: "21671",
		country: "Guinea",
		isActive: false,
	},
	{
		firstName: "Joel",
		lastName: "Jacobson",
		phone: "1-236-555-8245",
		email: "dui.Fusce@aarcuSed.ca",
		street: "9295 Sem. Avenue",
		city: "Erciş",
		postalCode: "73357",
		country: "Tokelau",
		isActive: false,
	},
	{
		firstName: "Cairo",
		lastName: "Wooten",
		phone: "706-5005",
		email: "tincidunt@etmagnis.co.uk",
		street: "P.O. Box 601, 2436 Convallis Ave",
		city: "Saint-Luc",
		postalCode: "096036",
		country: "Swaziland",
		isActive: false,
	},
	{
		firstName: "Kelsey",
		lastName: "Webb",
		phone: "1-638-392-3592",
		email: "sollicitudin.orci.sem@Sedeget.com",
		street: "6094 Luctus Av.",
		city: "Kenosha",
		postalCode: "61147",
		country: "Bonaire, Sint Eustatius and Saba",
		isActive: true,
	},
	{
		firstName: "Ulysses",
		lastName: "Bass",
		phone: "871-2291",
		email: "condimentum.eget@nequevitaesemper.net",
		street: "Ap #584-9453 Nascetur Rd.",
		city: "Kenosha",
		postalCode: "783360",
		country: "Mozambique",
		isActive: false,
	},
	{
		firstName: "Branden",
		lastName: "Olson",
		phone: "680-2284",
		email: "velit.Quisque.varius@ipsumnunc.co.uk",
		street: "7660 Aenean Avenue",
		city: "Rance",
		postalCode: "85157-480",
		country: "French Polynesia",
		isActive: false,
	},
	{
		firstName: "Hedley",
		lastName: "Fisher",
		phone: "1-567-756-2513",
		email: "vel.arcu.Curabitur@turpis.net",
		street: "5733 Interdum St.",
		city: "Subbiano",
		postalCode: "10562",
		country: "Grenada",
		isActive: true,
	},
	{
		firstName: "Joseph",
		lastName: "Vazquez",
		phone: "672-4070",
		email: "at.pede@iaculislacuspede.org",
		street: "Ap #518-5494 Ipsum St.",
		city: "Schifferstadt",
		postalCode: "58-971",
		country: "Benin",
		isActive: true,
	},
	{
		firstName: "Gretchen",
		lastName: "Randolph",
		phone: "340-5766",
		email: "mus@lacus.ca",
		street: "Ap #330-7832 Libero. Road",
		city: "Massa Martana",
		postalCode: "17588",
		country: "Mauritius",
		isActive: false,
	},
	{
		firstName: "Kenyon",
		lastName: "Odonnell",
		phone: "491-1344",
		email: "feugiat@eleifendegestas.co.uk",
		street: "P.O. Box 287, 3055 Ultricies Rd.",
		city: "Malartic",
		postalCode: "33239",
		country: "Gibraltar",
		isActive: false,
	},
	{
		firstName: "Jonas",
		lastName: "Pratt",
		phone: "574-0310",
		email: "cursus.et.magna@egestaslaciniaSed.co.uk",
		street: "5899 Odio. Avenue",
		city: "Couture-Saint-Germain",
		postalCode: "64627",
		country: "Kazakhstan",
		isActive: false,
	},
	{
		firstName: "Yen",
		lastName: "Fleming",
		phone: "1-170-461-3549",
		email: "quis.diam.luctus@ornareegestas.com",
		street: "4876 Feugiat Rd.",
		city: "Cametá",
		postalCode: "7876",
		country: "Syria",
		isActive: true,
	},
	{
		firstName: "Jeanette",
		lastName: "West",
		phone: "116-1075",
		email: "tempor.bibendum@Nullamnisl.ca",
		street: "P.O. Box 254, 7090 Quis, Street",
		city: "Whitby",
		postalCode: "14337",
		country: "Greece",
		isActive: false,
	},
	{
		firstName: "Ashton",
		lastName: "Kline",
		phone: "225-0907",
		email: "libero.Integer.in@magnased.net",
		street: "Ap #429-6475 Duis Avenue",
		city: "Ospedaletto d'Alpinolo",
		postalCode: "0895 XB",
		country: "French Polynesia",
		isActive: true,
	},
	{
		firstName: "Laura",
		lastName: "Roy",
		phone: "1-636-462-9796",
		email: "at.libero.Morbi@enim.org",
		street: "P.O. Box 664, 630 Dolor Rd.",
		city: "Deline",
		postalCode: "8056",
		country: "Dominica",
		isActive: false,
	},
	{
		firstName: "Ina",
		lastName: "Mercado",
		phone: "996-8262",
		email: "lobortis.ultrices.Vivamus@turpis.com",
		street: "976-2877 Pharetra. St.",
		city: "Sanghar",
		postalCode: "18676",
		country: "Azerbaijan",
		isActive: true,
	},
	{
		firstName: "Devin",
		lastName: "Soto",
		phone: "1-115-911-4937",
		email: "aliquam@eutellus.edu",
		street: "P.O. Box 449, 9394 Ac St.",
		city: "Gravataí",
		postalCode: "9365",
		country: "Rwanda",
		isActive: true,
	},
	{
		firstName: "Cameron",
		lastName: "Kirby",
		phone: "1-692-242-5841",
		email: "ut.ipsum.ac@sapienmolestie.com",
		street: "634-9063 Nec, Rd.",
		city: "Villach",
		postalCode: "4185",
		country: "Syria",
		isActive: false,
	},
	{
		firstName: "Mary",
		lastName: "Reilly",
		phone: "976-6944",
		email: "auctor.odio@velit.com",
		street: "P.O. Box 502, 8462 Magna Street",
		city: "College",
		postalCode: "2918",
		country: "Svalbard and Jan Mayen Islands",
		isActive: false,
	},
	{
		firstName: "Reuben",
		lastName: "Mckenzie",
		phone: "662-1645",
		email: "feugiat.metus@mollislectus.co.uk",
		street: "9029 Aptent Rd.",
		city: "Sluis",
		postalCode: "34367",
		country: "Andorra",
		isActive: false,
	},
	{
		firstName: "Hermione",
		lastName: "Obrien",
		phone: "1-881-495-7452",
		email: "ullamcorper.velit@tristique.co.uk",
		street: "9274 Mattis Avenue",
		city: "South Bend",
		postalCode: "611944",
		country: "Tuvalu",
		isActive: false,
	},
	{
		firstName: "Paloma",
		lastName: "Fields",
		phone: "1-561-951-4725",
		email: "Nunc.ut.erat@luctus.org",
		street: "2958 Nulla St.",
		city: "Wevelgem",
		postalCode: "98-312",
		country: "Marshall Islands",
		isActive: false,
	},
	{
		firstName: "Keane",
		lastName: "Berg",
		phone: "1-453-928-7356",
		email: "Donec.nibh.Quisque@amet.com",
		street: "4977 Eu St.",
		city: "Sorgà",
		postalCode: "50610",
		country: "Timor-Leste",
		isActive: false,
	},
	{
		firstName: "Lucius",
		lastName: "Finley",
		phone: "761-3407",
		email: "sed.dictum@lobortisquispede.edu",
		street: "6623 Aliquam Ave",
		city: "Río Ibáñez",
		postalCode: "V0J 7L8",
		country: "San Marino",
		isActive: true,
	},
];
